#!/usr/bin/env python3
"""AI-Powered Stock Video Matcher Agent.

Matches voiceover script segments to high-quality vertical/portrait stock video clips
from Pexels using OmniRoute (via OpenAI SDK) for strict, physical-visual search queries
and Fast-cut (FactoHolic / Shorts style) pacing.

Architecture:
- AI Gateway: OmniRoute via standard `openai` SDK (`OpenAI(base_url=..., api_key=...)`)
- Stock Video Provider: Pexels REST API (`https://api.pexels.com/videos/search`)
- Configuration: `python-dotenv` (.env)
- Output Formatting: `rich` table display and clean JSON serialization
"""

from __future__ import annotations

import argparse
import asyncio
import json
import math
import os
import re
import sys
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

import requests
from dotenv import load_dotenv
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# Reconfigure stdout/stderr for Unicode safety across Windows terminals
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

# Optional rich imports with graceful fallback
try:
    from rich import print as rprint
    from rich.console import Console
    from rich.panel import Panel
    from rich.progress import (
        BarColumn,
        DownloadColumn,
        Progress,
        SpinnerColumn,
        TextColumn,
        TimeRemainingColumn,
        TransferSpeedColumn,
    )
    from rich.table import Table
    RICH_AVAILABLE = True
except ImportError:
    RICH_AVAILABLE = False

# Try importing OpenAI SDK
try:
    from openai import APIConnectionError, APIError, APITimeoutError, OpenAI, RateLimitError
    OPENAI_AVAILABLE = True
except ImportError:
    OPENAI_AVAILABLE = False

# Load environment variables
load_dotenv()

# Banned words list (abstract concepts, emotions, buzzwords, non-visual terms)
BANNED_WORDS = {
    "expensive",
    "crazy",
    "shocking",
    "history",
    "unbelievable",
    "amazing",
    "success",
    "successful",
    "mystery",
    "wealthy",
    "rich",
    "poor",
    "sad",
    "happy",
    "secret",
    "dangerous",
    "danger",
    "future",
    "mind-blowing",
    "insane",
    "tragic",
    "tragedy",
    "historical",
    "financial",
    "emotional",
    "incredible",
    "epic",
    "wild",
    "scary",
    "fear",
    "wealth",
    "power",
    "powerful",
}


# ============================================================================
# Data Models
# ============================================================================


@dataclass
class ClipQuery:
    """Structured visual search query generated by LLM."""
    clip_index: int
    search_query: str
    shot_intent: str

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class VideoFileCandidate:
    """Represents a specific video quality/resolution file from Pexels."""
    id: int
    quality: str
    file_type: str
    width: int
    height: int
    fps: float
    link: str

    @property
    def resolution(self) -> str:
        return f"{self.width}x{self.height}"

    @property
    def is_portrait(self) -> bool:
        return self.height >= self.width

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class PexelsVideo:
    """Metadata for a matched Pexels video."""
    id: int
    url: str
    duration: int
    tags: List[str]
    user_name: str
    selected_file: Optional[VideoFileCandidate]
    was_fallback: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "url": self.url,
            "duration": self.duration,
            "tags": self.tags,
            "user_name": self.user_name,
            "selected_file": self.selected_file.to_dict() if self.selected_file else None,
            "was_fallback": self.was_fallback,
        }


@dataclass
class ClipMatch:
    """A matched segment pairing the generated query with Pexels footage."""
    clip_index: int
    query: ClipQuery
    video: Optional[PexelsVideo]
    download_path: Optional[str] = None
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "clip_index": self.clip_index,
            "query": self.query.to_dict(),
            "video": self.video.to_dict() if self.video else None,
            "download_path": self.download_path,
            "error": self.error,
        }


@dataclass
class StockMatcherResult:
    """Overall outcome of the stock matching process."""
    script_segment: str
    duration_seconds: float
    clip_count: int
    model_used: str
    matches: List[ClipMatch] = field(default_factory=list)
    execution_time_seconds: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "script_segment": self.script_segment,
            "duration_seconds": self.duration_seconds,
            "clip_count": self.clip_count,
            "model_used": self.model_used,
            "execution_time_seconds": round(self.execution_time_seconds, 2),
            "matches": [m.to_dict() for m in self.matches],
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)


# ============================================================================
# Visual Query Generator (OmniRoute / OpenAI SDK)
# ============================================================================


class VisualQueryGenerator:
    """Converts script segments into concrete, physical-only search queries via OmniRoute."""

    SYSTEM_PROMPT = """You are a visual director specializing in hyper-engaging vertical short-form video (FactoHolic / YouTube Shorts / Reels style).
Your task is to convert voiceover script segments into precise, visual-only stock footage search queries.

CRITICAL RULES:
1. Fast-cut pacing: Output EXACTLY {clip_count} queries (one for every 2.5 seconds of narration).
2. Word count: Each query MUST be between 3 and 5 words maximum in English.
3. CONCRETE PHYSICAL VISUALS ONLY:
   - Describe only physical objects, environments, camera movements, textures, and visible actions that a camera lens can record.
   - Example good queries: "drone aerial luxury mansion", "counting dollar bills hands", "private jet interior", "futuristic server room glowing", "person opening steel vault".
4. STRICT BAN ON ABSTRACT & EMOTIONAL WORDS:
   - You MUST NOT use abstract concepts, emotions, or buzzwords.
   - BANNED WORDS include: "expensive", "crazy", "shocking", "history", "wealthy", "rich", "poor", "sad", "happy", "secret", "dangerous", "unbelievable", "amazing", "success", "power", "mind-blowing", "financial".
   - Instead of "expensive mansion" -> use "drone aerial luxury mansion"
   - Instead of "crazy money" -> use "counting dollar bills hands"
   - Instead of "shocking secret document" -> use "hands opening classified dossier"
   - Instead of "ancient history" -> use "pyramids desert sand golden hour"
5. OUTPUT FORMAT:
   Return valid, parsable JSON ONLY without any additional explanation or conversational text, adhering to this schema:
   {
     "clips": [
       {
         "clip_index": 1,
         "search_query": "3 to 5 words visual query",
         "shot_intent": "brief 1-sentence description of the visual scene"
       }
     ]
   }
"""

    def __init__(
        self,
        base_url: Optional[str] = None,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        timeout: float = 30.0,
    ) -> None:
        if not OPENAI_AVAILABLE:
            raise ImportError(
                "The `openai` package is required. Install it using: pip install openai"
            )

        # Environment variable precedence: explicit -> OMNIROUTE_BASE_URL -> OMNIROUTE_BASE -> default
        self.base_url = (
            base_url
            or os.getenv("OMNIROUTE_BASE_URL")
            or os.getenv("OMNIROUTE_BASE")
            or "http://127.0.0.1:20128/v1"
        )
        self.api_key = (
            api_key
            or os.getenv("OMNIROUTE_API_KEY")
            or os.getenv("OMNIROUTE_KEY")
            or "omniroute"
        )
        self.model = (
            model
            or os.getenv("OMNIROUTE_MODEL")
            or os.getenv("RAHASYA_MODEL_CHEAP")
            or "agy/gemini-3.7-flash-medium"
        )
        self.timeout = timeout

        self.client = OpenAI(
            base_url=self.base_url,
            api_key=self.api_key,
            timeout=self.timeout,
        )

    def calculate_clip_count(self, duration_seconds: float) -> int:
        """Calculate clip count: math.ceil(duration_seconds / 2.5)."""
        duration = max(1.0, float(duration_seconds))
        return max(1, math.ceil(duration / 2.5))

    def _sanitize_query(self, raw_query: str) -> str:
        """Sanitize query: remove punctuation, ban list words, enforce 3-5 words."""
        # Strip quotes and punctuation
        clean = re.sub(r'[^\w\s]', ' ', raw_query).strip()
        words = clean.split()

        # Filter out banned words (case-insensitive)
        filtered_words = [w for w in words if w.lower() not in BANNED_WORDS]

        # If too few words after filtering, fallback to non-banned or basic visuals
        if not filtered_words:
            filtered_words = ["cinematic", "visual", "shot"]

        # Enforce 3 to 5 words
        if len(filtered_words) > 5:
            filtered_words = filtered_words[:5]
        elif len(filtered_words) < 3:
            # Pad with complementary physical terms if needed
            fillers = ["4k", "cinematic", "macro", "detail"]
            for filler in fillers:
                if len(filtered_words) >= 3:
                    break
                if filler not in filtered_words:
                    filtered_words.append(filler)

        return " ".join(filtered_words).lower()

    def generate_queries(
        self, script_segment: str, duration_seconds: float
    ) -> Tuple[List[ClipQuery], int]:
        """Generate structured visual queries from the script segment."""
        clip_count = self.calculate_clip_count(duration_seconds)
        system_prompt = self.SYSTEM_PROMPT.replace("{clip_count}", str(clip_count))
        user_prompt = f"VOICEOVER SCRIPT SEGMENT ({duration_seconds:.1f}s):\n\"{script_segment}\""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.3,
            )
        except (APIError, APIConnectionError, APITimeoutError, RateLimitError) as exc:
            raise RuntimeError(f"OmniRoute LLM generation failed: {exc}") from exc

        content = response.choices[0].message.content or ""
        parsed_clips = self._parse_json_response(content, clip_count)

        # Sanitize and post-process
        validated_queries: List[ClipQuery] = []
        for idx, item in enumerate(parsed_clips, start=1):
            raw_query = item.get("search_query", "")
            shot_intent = item.get("shot_intent", "Visual scene support")
            clean_query = self._sanitize_query(raw_query)
            validated_queries.append(
                ClipQuery(
                    clip_index=idx,
                    search_query=clean_query,
                    shot_intent=shot_intent,
                )
            )

        return validated_queries, clip_count

    def generate_mock_queries(
        self, script_segment: str, duration_seconds: float
    ) -> Tuple[List[ClipQuery], int]:
        """Generate deterministic, high-quality visual queries for mock/offline testing."""
        clip_count = self.calculate_clip_count(duration_seconds)
        visual_pool = [
            ("drone aerial mountain fortress", "Establishing shot of remote mountain complex"),
            ("heavy steel vault door", "Close-up of industrial security door locking mechanism"),
            ("gold bars stacked rows", "Camera dolly over gleaming metal ingots"),
            ("security laser beams corridor", "Low angle of high-tech surveillance hallway"),
            ("counting dollar bills hands", "Close-up of currency passing rapidly through fingers"),
            ("private jet hangar exterior", "Wide view of private aircraft on runway tarmac"),
            ("futuristic server room glowing", "Dolly shot down dark server aisles with blue LEDs"),
            ("hands typing glowing keyboard", "Macro shot of fingers entering security codes"),
        ]
        queries: List[ClipQuery] = []
        for i in range(clip_count):
            query_tuple = visual_pool[i % len(visual_pool)]
            clean_q = self._sanitize_query(query_tuple[0])
            queries.append(
                ClipQuery(
                    clip_index=i + 1,
                    search_query=clean_q,
                    shot_intent=query_tuple[1],
                )
            )
        return queries, clip_count

    def _parse_json_response(self, content: str, expected_count: int) -> List[Dict[str, Any]]:
        """Parse structured JSON from model response with fallback extraction."""
        # Clean markdown codeblocks
        cleaned = content.strip()
        if "```" in cleaned:
            match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", cleaned)
            if match:
                cleaned = match.group(1).strip()

        try:
            data = json.loads(cleaned)
            if isinstance(data, dict) and "clips" in data and isinstance(data["clips"], list):
                return data["clips"]
            if isinstance(data, list):
                return data
        except json.JSONDecodeError:
            pass

        # Fallback: regex search for clip-like JSON objects
        matches = re.findall(
            r'\{\s*"clip_index"\s*:\s*\d+\s*,\s*"search_query"\s*:\s*"([^"]+)"\s*,\s*"shot_intent"\s*:\s*"([^"]+)"\s*\}',
            content,
        )
        if matches:
            return [
                {"clip_index": i + 1, "search_query": q, "shot_intent": intent}
                for i, (q, intent) in enumerate(matches)
            ]

        # Last resort fallback: line-by-line fallback
        lines = [line.strip("- *0123456789.:\" ") for line in content.splitlines() if line.strip()]
        valid_lines = [l for l in lines if len(l.split()) >= 2][:expected_count]
        if not valid_lines:
            valid_lines = [f"cinematic shot clip {i+1}" for i in range(expected_count)]

        return [
            {
                "clip_index": idx + 1,
                "search_query": line,
                "shot_intent": f"Scene visual for segment {idx + 1}",
            }
            for idx, line in enumerate(valid_lines)
        ]


# ============================================================================
# Pexels Video Fetcher & Re-ranker
# ============================================================================

# The renderer's output frame size, in pixels (1080x1920). This MUST match
# engine/media rendering's actual output resolution: every downloaded clip is
# scaled to this size before compositing, so picking a source file far above
# it only burns bandwidth/disk/CPU on pixels that get thrown away, and picking
# one below it forces an upscale that never looks as good as a downscale.
RENDER_TARGET_WIDTH = 1080
RENDER_TARGET_HEIGHT = 1920
RENDER_TARGET_PIXELS = RENDER_TARGET_WIDTH * RENDER_TARGET_HEIGHT  # 2,073,600

# _select_best_video scoring bands (see the resolution-scoring comment
# there for the full rationale). The orientation bonus must stay the
# dominant term: a correctly-oriented file must outscore a wrongly-oriented
# one no matter what the other terms award. Those other terms are the
# resolution score AND the HD-quality bonus, and they are summed, so the
# comparison that matters is against their combined maximum
# (_RESOLUTION_COVER_CEILING + _HD_QUALITY_BONUS = 4,500,000), not against
# the resolution term alone. Real headroom under ORIENTATION_BONUS is
# 500,000. Within the resolution term, the "covers the target" band is
# [_RESOLUTION_COVER_FLOOR, _RESOLUTION_COVER_CEILING] = [2,000,000,
# 4,000,000] and the "undersized" band is [0, _RESOLUTION_UNDERSIZED_CEILING)
# = [0, 1,000,000) — the bands don't overlap, so every covering file
# outscores every undersized one.
#
# These asserts document the invariants; note they are stripped under
# `python -O`, so they are a statement of intent for whoever edits the
# numbers, not a runtime guard. Keep them honest.
ORIENTATION_BONUS = 5_000_000.0
_RESOLUTION_COVER_CEILING = 4_000_000.0
_RESOLUTION_COVER_FLOOR = 2_000_000.0
_RESOLUTION_UNDERSIZED_CEILING = 1_000_000.0
# Awarded on top of the resolution score when Pexels flags a file "hd".
_HD_QUALITY_BONUS = 500_000.0
assert _RESOLUTION_COVER_CEILING + _HD_QUALITY_BONUS < ORIENTATION_BONUS
assert _RESOLUTION_UNDERSIZED_CEILING < _RESOLUTION_COVER_FLOOR < _RESOLUTION_COVER_CEILING


class PexelsFetcher:
    """Queries Pexels Videos API with portrait filters, HD MP4 selection, and landscape fallback."""

    BASE_URL = "https://api.pexels.com/videos/search"

    def __init__(self, api_key: Optional[str] = None, timeout: float = 15.0) -> None:
        self.api_key = api_key or os.getenv("PEXELS_API_KEY") or ""
        self.timeout = timeout

        self.session = requests.Session()
        retries = Retry(
            total=3,
            backoff_factor=1.0,
            status_forcelist=[429, 500, 502, 503, 504],
            allowed_methods=["GET"],
        )
        self.session.mount("https://", HTTPAdapter(max_retries=retries))

    def _headers(self) -> Dict[str, str]:
        if not self.api_key:
            raise ValueError(
                "PEXELS_API_KEY is not set. Please add it to your .env file or pass api_key."
            )
        return {"Authorization": self.api_key}

    def search_video(
        self,
        query: str,
        orientation: str = "portrait",
        per_page: int = 5,
    ) -> Tuple[Optional[PexelsVideo], bool]:
        """Search Pexels for a query with portrait priority and landscape fallback.

        Returns:
            Tuple of (PexelsVideo or None, was_fallback_boolean)
        """
        # Step 1: Search preferred orientation (portrait)
        videos, was_fallback = self._execute_search(query, orientation=orientation, per_page=per_page)
        
        # Step 2: Fallback to landscape if 0 results
        if not videos and orientation == "portrait":
            videos, _ = self._execute_search(query, orientation="landscape", per_page=per_page)
            was_fallback = True

        # Step 3: Fallback to no orientation filter if still 0 results
        if not videos:
            videos, _ = self._execute_search(query, orientation=None, per_page=per_page)
            was_fallback = True

        # Step 4: Fallback to simplified query (first 2 words) if still 0
        if not videos:
            simplified_query = " ".join(query.split()[:2])
            if simplified_query and simplified_query != query:
                videos, _ = self._execute_search(simplified_query, orientation=None, per_page=per_page)
                was_fallback = True

        if not videos:
            return None, was_fallback

        # Re-rank and extract the best MP4 file from the top matching video
        best_video = self._select_best_video(videos, target_portrait=(orientation == "portrait"))
        if best_video:
            best_video.was_fallback = was_fallback

        return best_video, was_fallback

    def mock_video(self, query: str, clip_index: int = 1) -> Tuple[PexelsVideo, bool]:
        """Return simulated portrait HD video result for offline testing."""
        sample_file = VideoFileCandidate(
            id=1000 + clip_index,
            quality="hd",
            file_type="video/mp4",
            width=1080,
            height=1920,
            fps=30.0,
            link=f"https://static.pexels.com/mock/clip_{clip_index:02d}_1080x1920.mp4",
        )
        video = PexelsVideo(
            id=2000 + clip_index,
            url=f"https://www.pexels.com/video/{2000 + clip_index}/",
            duration=15,
            tags=query.split(),
            user_name="StockCinematographer",
            selected_file=sample_file,
            was_fallback=False,
        )
        return video, False

    def _execute_search(
        self,
        query: str,
        orientation: Optional[str] = None,
        per_page: int = 5,
    ) -> Tuple[List[Dict[str, Any]], bool]:
        """Execute HTTP GET to Pexels video search endpoint."""
        params: Dict[str, Any] = {"query": query, "per_page": per_page}
        if orientation:
            params["orientation"] = orientation

        try:
            resp = self.session.get(
                self.BASE_URL,
                headers=self._headers(),
                params=params,
                timeout=self.timeout,
            )
            resp.raise_for_status()
            data = resp.json()
            return data.get("videos", []), False
        except requests.RequestException as err:
            # Handle rate limit or network timeout
            if isinstance(err, requests.HTTPError) and err.response is not None and err.response.status_code == 401:
                raise ValueError("Invalid PEXELS_API_KEY. Please verify your Pexels credentials.") from err
            return [], False

    def _select_best_video(
        self,
        videos: List[Dict[str, Any]],
        target_portrait: bool = True,
    ) -> Optional[PexelsVideo]:
        """Select the highest resolution MP4 matching target orientation from candidate videos."""
        best_video_obj: Optional[PexelsVideo] = None
        highest_score = -1.0

        for vid in videos:
            video_id = vid.get("id", 0)
            url = vid.get("url", "")
            duration = int(vid.get("duration", 0))
            tags = [t.get("name", "") if isinstance(t, dict) else str(t) for t in vid.get("tags", [])]
            user = vid.get("user", {})
            user_name = user.get("name", "") if isinstance(user, dict) else ""

            # Evaluate video_files
            video_files = vid.get("video_files", [])
            best_file: Optional[VideoFileCandidate] = None
            best_file_score = -1.0

            for f in video_files:
                file_type = f.get("file_type", "")
                link = f.get("link", "")
                
                # Must be MP4
                if file_type != "video/mp4" and not link.endswith(".mp4"):
                    continue

                width = int(f.get("width") or 0)
                height = int(f.get("height") or 0)
                fps = float(f.get("fps") or 0.0)
                quality = str(f.get("quality") or "sd").lower()

                if width <= 0 or height <= 0 or not link:
                    continue

                # Scoring criteria:
                # 1. Aspect ratio: bonus if matches target orientation
                is_portrait = height >= width
                score = 0.0
                if target_portrait and is_portrait:
                    score += ORIENTATION_BONUS
                elif not target_portrait and not is_portrait:
                    score += ORIENTATION_BONUS

                # 2. Prefer the smallest file that still covers the render
                # target (1080x1920) over the largest one available: every
                # pixel above the target is downloaded, decoded and then
                # scaled away by the renderer, so "biggest wins" wastes
                # bandwidth/disk/time for no visual benefit.
                #
                # - At/above target: closer to the target (from above) is
                #   better. Score falls off monotonically as pixel_count
                #   grows past the target, so a smaller covering file always
                #   outscores a larger one, but the score is floored at
                #   _RESOLUTION_COVER_FLOOR so it can never sink into (let
                #   alone below) the undersized band.
                # - Below target: acceptable only when nothing covers the
                #   target; among those, bigger is better (less upscaling),
                #   but the whole band is capped by _RESOLUTION_UNDERSIZED_CEILING,
                #   which sits strictly below _RESOLUTION_COVER_FLOOR — so no
                #   undersized file can ever outscore a covering one.
                #
                # The resolution term's maximum (_RESOLUTION_COVER_CEILING)
                # plus the HD bonus is kept strictly below ORIENTATION_BONUS
                # (see the constants), so a correctly-oriented file always
                # beats a wrongly-oriented one regardless of resolution or
                # quality flag.
                pixel_count = width * height
                if pixel_count >= RENDER_TARGET_PIXELS:
                    coverage_ratio = RENDER_TARGET_PIXELS / pixel_count  # (0, 1], 1.0 = exact match
                    resolution_score = _RESOLUTION_COVER_FLOOR + (
                        _RESOLUTION_COVER_CEILING - _RESOLUTION_COVER_FLOOR
                    ) * coverage_ratio
                else:
                    undersize_ratio = pixel_count / RENDER_TARGET_PIXELS  # [0, 1)
                    resolution_score = _RESOLUTION_UNDERSIZED_CEILING * undersize_ratio
                score += resolution_score

                # 3. Quality flag bonus
                if quality == "hd":
                    score += _HD_QUALITY_BONUS

                if score > best_file_score:
                    best_file_score = score
                    best_file = VideoFileCandidate(
                        id=f.get("id", 0),
                        quality=quality,
                        file_type=file_type,
                        width=width,
                        height=height,
                        fps=fps,
                        link=link,
                    )

            if best_file and best_file_score > highest_score:
                highest_score = best_file_score
                best_video_obj = PexelsVideo(
                    id=video_id,
                    url=url,
                    duration=duration,
                    tags=tags,
                    user_name=user_name,
                    selected_file=best_file,
                )

        return best_video_obj


# ============================================================================
# Download Pipeline
# ============================================================================


class ClipDownloader:
    """Streams and downloads video files sequentially with progress tracking."""

    def __init__(self, output_dir: str = "output_clips", timeout: float = 60.0) -> None:
        self.output_dir = Path(output_dir)
        self.timeout = timeout
        self.session = requests.Session()

    def download_clip(
        self,
        url: str,
        clip_index: int,
        progress: Optional[Progress] = None,
        task_id: Any = None,
        output_dir: Optional[Union[str, Path]] = None,
    ) -> Path:
        """Download video from URL directly into <output_dir>/clip_{index:02d}.mp4 atomically.

        ``output_dir`` is per call and overrides ``self.output_dir``. It
        exists because a single downloader is shared by concurrent
        ``StockVideoMatcherAgent.match()`` calls: a destination *stored* on
        the instance is whatever the most recent caller wrote there, which
        sent one beat's clips into another beat's folder (and raced on the
        ``.tmp`` staging path, so a half-written file could be renamed over
        a finished one). A destination *passed* cannot be clobbered by
        another thread. ``self.output_dir`` remains the default for
        single-threaded callers.
        """
        target_dir = Path(output_dir) if output_dir is not None else self.output_dir
        target_dir.mkdir(parents=True, exist_ok=True)
        filename = f"clip_{clip_index:02d}.mp4"
        final_path = target_dir / filename
        temp_path = target_dir / f"{filename}.tmp"

        # Fast-path for mock testing URLs
        if url.startswith("https://static.pexels.com/mock/") or url.startswith("mock://"):
            mock_bytes = b"\x00\x00\x00\x20ftypisom\x00\x00\x02\x00isomiso2avc1mp41" + (b"\x00" * (1024 * 128))
            if progress and task_id is not None:
                progress.update(task_id, total=len(mock_bytes))
                progress.update(task_id, advance=len(mock_bytes))
            final_path.write_bytes(mock_bytes)
            return final_path

        try:
            with self.session.get(url, stream=True, timeout=self.timeout) as response:
                response.raise_for_status()
                total_size = int(response.headers.get("content-length", 0))

                if progress and task_id is not None:
                    progress.update(task_id, total=total_size)

                with open(temp_path, "wb") as f:
                    for chunk in response.iter_content(chunk_size=1024 * 64):
                        if chunk:
                            f.write(chunk)
                            if progress and task_id is not None:
                                progress.update(task_id, advance=len(chunk))

            # Atomic rename once complete
            temp_path.replace(final_path)
            return final_path
        except Exception:
            if temp_path.exists():
                temp_path.unlink()
            raise


# ============================================================================
# Main Agent Orchestrator
# ============================================================================


class StockVideoMatcherAgent:
    """End-to-end AI-Powered Stock Video Matcher Agent."""

    def __init__(
        self,
        omniroute_base_url: Optional[str] = None,
        omniroute_api_key: Optional[str] = None,
        omniroute_model: Optional[str] = None,
        pexels_api_key: Optional[str] = None,
    ) -> None:
        self.query_generator = VisualQueryGenerator(
            base_url=omniroute_base_url,
            api_key=omniroute_api_key,
            model=omniroute_model,
        )
        self.pexels_fetcher = PexelsFetcher(api_key=pexels_api_key)
        self.downloader = ClipDownloader()

    def match(
        self,
        script_segment: str,
        duration_seconds: float,
        download: bool = False,
        output_dir: str = "output_clips",
        on_query_ready: Optional[Any] = None,
        mock: bool = False,
    ) -> StockMatcherResult:
        """Synchronously match stock footage to script segment.

        Args:
            script_segment: The voiceover narration text.
            duration_seconds: Runtime in seconds.
            download: If True, downloads MP4s to output_dir.
            output_dir: Folder to save downloaded MP4 clips.
            on_query_ready: Optional callback receiving generated queries.
            mock: If True, uses deterministic offline mock generation.

        Returns:
            StockMatcherResult containing all queries, matches, and file paths.
        """
        start_time = time.time()
        # output_dir is carried in a local and handed to each download_clip
        # call below; it is deliberately NOT stored on self.downloader.
        # match() is re-entrant: engine/pipeline.py builds ONE agent and
        # engine/media/clips.generate_plan_clips runs beats through a
        # 4-worker pool, and seconds pass between here and the downloads —
        # an LLM round trip plus a Pexels search per clip. Recording the
        # destination on the shared downloader therefore meant a beat
        # downloaded into whichever directory the most recently *started*
        # call had asked for, not its own: clip_NN.mp4 names collided
        # across beats again, and the clip_NN.mp4.tmp staging path raced,
        # so a half-written file could be renamed over a finished one.
        # Nothing here may mutate self (or anything reachable from it).

        # 1. Generate queries via OmniRoute or Mock
        if mock:
            queries, clip_count = self.query_generator.generate_mock_queries(
                script_segment=script_segment,
                duration_seconds=duration_seconds,
            )
        else:
            queries, clip_count = self.query_generator.generate_queries(
                script_segment=script_segment,
                duration_seconds=duration_seconds,
            )

        if on_query_ready:
            on_query_ready(queries)

        matches: List[ClipMatch] = []

        # 2. Fetch stock videos for each query
        for query in queries:
            try:
                if mock or not self.pexels_fetcher.api_key:
                    matched_video, was_fallback = self.pexels_fetcher.mock_video(
                        query=query.search_query,
                        clip_index=query.clip_index,
                    )
                else:
                    matched_video, was_fallback = self.pexels_fetcher.search_video(
                        query=query.search_query,
                        orientation="portrait",
                        per_page=5,
                    )
                match_entry = ClipMatch(
                    clip_index=query.clip_index,
                    query=query,
                    video=matched_video,
                    error=None if matched_video else "No stock video found for query",
                )
            except Exception as exc:
                match_entry = ClipMatch(
                    clip_index=query.clip_index,
                    query=query,
                    video=None,
                    error=str(exc),
                )
            matches.append(match_entry)

        # 3. Optional download pipeline
        if download:
            for match in matches:
                if match.video and match.video.selected_file:
                    try:
                        saved_path = self.downloader.download_clip(
                            url=match.video.selected_file.link,
                            clip_index=match.clip_index,
                            output_dir=output_dir,
                        )
                        match.download_path = str(saved_path)
                    except Exception as err:
                        match.error = f"Download failed: {err}"

        elapsed = time.time() - start_time
        return StockMatcherResult(
            script_segment=script_segment,
            duration_seconds=duration_seconds,
            clip_count=clip_count,
            model_used=self.query_generator.model if not mock else "mock-generator",
            matches=matches,
            execution_time_seconds=elapsed,
        )

    async def match_async(
        self,
        script_segment: str,
        duration_seconds: float,
        download: bool = False,
        output_dir: str = "output_clips",
        mock: bool = False,
    ) -> StockMatcherResult:
        """Asynchronously execute matching via asyncio thread pool."""
        return await asyncio.to_thread(
            self.match,
            script_segment=script_segment,
            duration_seconds=duration_seconds,
            download=download,
            output_dir=output_dir,
            mock=mock,
        )


# ============================================================================
# CLI Presentation Helpers
# ============================================================================


def render_rich_output(
    console: Console,
    result: StockMatcherResult,
    show_downloads: bool = False,
) -> None:
    """Render a polished, executive-ready terminal display using Rich."""
    try:
        # Header Banner
        banner = Panel(
            f"[bold cyan]AI-Powered Stock Video Matcher[/bold cyan]\n"
            f"[dim]OmniRoute Gateway ({result.model_used}) + Pexels HD Portrait API[/dim]",
            border_style="cyan",
            expand=False,
        )
        console.print(banner)

        # Input Summary Table
        summary_table = Table(show_header=False, box=None, padding=(0, 2))
        summary_table.add_column("Key", style="bold yellow")
        summary_table.add_column("Value", style="white")

        script_preview = (
            result.script_segment[:90] + "..."
            if len(result.script_segment) > 90
            else result.script_segment
        )
        summary_table.add_row("Script Segment", f'"{script_preview}"')
        summary_table.add_row("Duration", f"{result.duration_seconds:.1f}s")
        summary_table.add_row("Pacing Formula", f"ceil({result.duration_seconds:.1f} / 2.5) = {result.clip_count} cuts")
        summary_table.add_row("Execution Time", f"{result.execution_time_seconds:.2f}s")
        console.print(Panel(summary_table, title="Input & Pacing Overview", border_style="dim"))

        # Results Table
        results_table = Table(
            title="[bold green]Matched Stock Video Timeline[/bold green]",
            border_style="blue",
            header_style="bold magenta",
            expand=True,
        )
        results_table.add_column("#", style="cyan", width=4, justify="center")
        results_table.add_column("Visual Search Query", style="bold white", width=26)
        results_table.add_column("Shot Intent", style="italic dim", width=28)
        results_table.add_column("Status / Fallback", style="yellow", width=18)
        results_table.add_column("Resolution", style="green", width=12)
        results_table.add_column("Pexels Link / Local File", style="blue")

        for m in result.matches:
            idx_str = f"{m.clip_index:02d}"
            query_str = m.query.search_query
            intent_str = m.query.shot_intent

            if m.video and m.video.selected_file:
                file_meta = m.video.selected_file
                status_str = "[green][OK] Portrait[/green]" if not m.video.was_fallback else "[yellow][FALLBACK] Landscape[/yellow]"
                res_str = f"{file_meta.resolution} ({file_meta.quality.upper()})"
                
                if m.download_path:
                    link_display = f"[bold green]Saved:[/bold green] {m.download_path}"
                else:
                    link_display = f"{file_meta.link[:35]}... (Pexels #{m.video.id})"
            else:
                status_str = "[red][FAIL][/red]"
                res_str = "N/A"
                link_display = f"[red]{m.error or 'Not found'}[/red]"

            results_table.add_row(idx_str, query_str, intent_str, status_str, res_str, link_display)

        console.print(results_table)
    except (UnicodeEncodeError, Exception):
        # Fallback to clean formatted JSON if terminal encoding fails
        print(result.to_json(indent=2))


# ============================================================================
# CLI Execution Block
# ============================================================================


def main() -> int:
    parser = argparse.ArgumentParser(
        description="AI-Powered Stock Video Matcher: Convert narration into high-res stock video cuts."
    )
    parser.add_argument(
        "script",
        nargs="?",
        help="Voiceover script segment (or specify via -s / --script).",
    )
    parser.add_argument(
        "-s",
        "--script-text",
        dest="script_flag",
        help="Voiceover script string directly.",
    )
    parser.add_argument(
        "-f",
        "--script-file",
        help="Path to a text file containing the script segment.",
    )
    parser.add_argument(
        "-d",
        "--duration",
        type=float,
        default=7.5,
        help="Voiceover duration in seconds (default: 7.5s -> 3 cuts).",
    )
    parser.add_argument(
        "--download",
        action="store_true",
        help="Download matched MP4 clips to output directory.",
    )
    parser.add_argument(
        "-o",
        "--output-dir",
        default="output_clips",
        help="Directory to save downloaded clips (default: output_clips).",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        dest="output_json",
        help="Output raw JSON format to stdout.",
    )
    parser.add_argument(
        "--model",
        help="Override OmniRoute model name (e.g. agy/gemini-3.7-flash-medium).",
    )
    parser.add_argument(
        "--base-url",
        help="Override OmniRoute base URL.",
    )
    parser.add_argument(
        "--mock",
        "--dry-run",
        action="store_true",
        dest="mock",
        help="Run in mock/offline mode (simulates OmniRoute AI queries and Pexels video metadata).",
    )

    args = parser.parse_args()

    # Determine script content
    script_content = ""
    if args.script_file:
        file_path = Path(args.script_file)
        if not file_path.exists():
            print(f"Error: Script file not found: {args.script_file}", file=sys.stderr)
            return 1
        script_content = file_path.read_text(encoding="utf-8").strip()
    elif args.script_flag:
        script_content = args.script_flag.strip()
    elif args.script:
        script_content = args.script.strip()
    else:
        # Default sample script for fast testing
        script_content = (
            "Deep inside the Swiss Alps lies an ultra-secure subterranean vault, "
            "where billionaires store metric tons of pure gold bars behind twenty-ton blast doors."
        )

    console = Console() if RICH_AVAILABLE else None

    # Check Pexels API key early
    pexels_key = os.getenv("PEXELS_API_KEY")
    if not pexels_key and not args.mock:
        msg = (
            "Notice: PEXELS_API_KEY is not set in environment or .env file.\n"
            "Query generation will succeed, but video search requires a free Pexels key from https://www.pexels.com/api/\n"
            "(Tip: Use --mock to test full visual rendering and downloads offline)."
        )
        if console and not args.output_json:
            console.print(f"[bold yellow]{msg}[/bold yellow]\n")
        else:
            print(msg, file=sys.stderr)

    try:
        agent = StockVideoMatcherAgent(
            omniroute_base_url=args.base_url,
            omniroute_model=args.model,
            pexels_api_key=pexels_key,
        )

        status_msg = (
            "[bold cyan]Generating visual queries via OmniRoute...[/bold cyan]"
            if not args.mock
            else "[bold cyan]Generating mock visual queries and stock video matches...[/bold cyan]"
        )

        # Execute query generation & matching
        if console and not args.output_json:
            with console.status(status_msg):
                result = agent.match(
                    script_segment=script_content,
                    duration_seconds=args.duration,
                    download=False,
                    output_dir=args.output_dir,
                    mock=args.mock,
                )
        else:
            result = agent.match(
                script_segment=script_content,
                duration_seconds=args.duration,
                download=False,
                output_dir=args.output_dir,
                mock=args.mock,
            )

        # Handle downloads with Rich progress if requested
        if args.download:
            # The CLI downloads outside match() (it wants a Rich progress
            # bar per clip), so it names --output-dir itself. match() used
            # to leave the destination on agent.downloader as a side
            # effect; it no longer does, because that shared mutation raced
            # when match() is called concurrently.
            clips_to_download = [m for m in result.matches if m.video and m.video.selected_file]
            if clips_to_download:
                if console and not args.output_json:
                    with Progress(
                        SpinnerColumn(),
                        TextColumn("[progress.description]{task.description}"),
                        BarColumn(),
                        DownloadColumn(),
                        TransferSpeedColumn(),
                        TimeRemainingColumn(),
                        console=console,
                    ) as progress:
                        for m in clips_to_download:
                            task = progress.add_task(
                                f"Downloading clip_{m.clip_index:02d}.mp4",
                                total=None,
                            )
                            try:
                                saved_path = agent.downloader.download_clip(
                                    url=m.video.selected_file.link,
                                    clip_index=m.clip_index,
                                    progress=progress,
                                    task_id=task,
                                    output_dir=args.output_dir,
                                )
                                m.download_path = str(saved_path)
                            except Exception as err:
                                m.error = f"Download failed: {err}"
                else:
                    for m in clips_to_download:
                        try:
                            saved_path = agent.downloader.download_clip(
                                url=m.video.selected_file.link,
                                clip_index=m.clip_index,
                                output_dir=args.output_dir,
                            )
                            m.download_path = str(saved_path)
                        except Exception as err:
                            m.error = f"Download failed: {err}"

        # Output format
        if args.output_json or not RICH_AVAILABLE:
            print(result.to_json(indent=2))
        else:
            render_rich_output(console, result, show_downloads=args.download)

        return 0

    except Exception as err:
        if args.output_json:
            print(json.dumps({"error": str(err)}, indent=2), file=sys.stderr)
        elif console:
            console.print(f"[bold red]Execution Error:[/bold red] {err}")
        else:
            print(f"Error: {err}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
