#!/usr/bin/env python3
"""AI-Powered Stock Video Matcher Agent.

Matches voiceover script segments to high-quality vertical/portrait stock video clips
from Pexels using OmniRoute (via OpenAI SDK) for strict, physical-visual search queries
and Fast-cut (FactoHolic / Shorts style) pacing.

Architecture:
- AI Gateway: OmniRoute via standard `openai` SDK (`OpenAI(base_url=..., api_key=...)`)
- Stock Video Provider: Pexels REST API (`https://api.pexels.com/videos/search`)
- Configuration: `python-dotenv` (.env)
- Output Formatting: `rich` table display and clean JSON serialization
"""

from __future__ import annotations

import argparse
import asyncio
import json
import math
import os
import re
import sys
import threading
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

import requests
from dotenv import load_dotenv
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# Reconfigure stdout/stderr for Unicode safety across Windows terminals
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

# Optional rich imports with graceful fallback
try:
    from rich import print as rprint
    from rich.console import Console
    from rich.panel import Panel
    from rich.progress import (
        BarColumn,
        DownloadColumn,
        Progress,
        SpinnerColumn,
        TextColumn,
        TimeRemainingColumn,
        TransferSpeedColumn,
    )
    from rich.table import Table
    RICH_AVAILABLE = True
except ImportError:
    RICH_AVAILABLE = False

# Try importing OpenAI SDK
try:
    from openai import APIConnectionError, APIError, APITimeoutError, OpenAI, RateLimitError
    OPENAI_AVAILABLE = True
except ImportError:
    OPENAI_AVAILABLE = False

# Load environment variables
load_dotenv()

# Banned words list (abstract concepts, emotions, buzzwords, non-visual terms)
# Dropped before a scene description is cut down to a query. Pexels
# ranks on content words, and "A close-up of a smartphone..." truncated to
# its first five words is "a close up of a", which matches nothing. With
# these gone the same sentence gives "close up smartphone playing
# youtube".
#
# Deliberately only function words -- articles, prepositions, conjunctions,
# auxiliaries, and the handful of framing verbs a shot description always
# opens with. Anything that names a thing, an action or a place has to
# survive, because that is the whole query.
SCENE_STOPWORDS = {
    "a", "an", "the", "of", "on", "in", "at", "by", "for", "from", "to",
    "with", "into", "onto", "over", "under", "near", "against", "across",
    "beside", "behind", "beneath", "between", "through", "during",
    "before", "after", "above", "below", "around", "along", "upon",
    "toward", "towards",
    "and", "or", "but", "as", "while", "then", "than", "that", "this",
    "these", "those", "there", "here", "its", "their", "his", "her",
    "is", "are", "was", "were", "be", "being", "been", "am",
    "shot", "showing", "shows", "show", "view", "image", "footage",
}

BANNED_WORDS = {
    "expensive",
    "crazy",
    "shocking",
    "history",
    "unbelievable",
    "amazing",
    "success",
    "successful",
    "mystery",
    "wealthy",
    "rich",
    "poor",
    "sad",
    "happy",
    "secret",
    "dangerous",
    "danger",
    "future",
    "mind-blowing",
    "insane",
    "tragic",
    "tragedy",
    "historical",
    "financial",
    "emotional",
    "incredible",
    "epic",
    "wild",
    "scary",
    "fear",
    "wealth",
    "power",
    "powerful",
}


# ============================================================================
# Data Models
# ============================================================================


@dataclass
class ClipQuery:
    """Structured visual search query generated by LLM."""
    clip_index: int
    search_query: str
    shot_intent: str

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class VideoFileCandidate:
    """Represents a specific video quality/resolution file from Pexels."""
    id: int
    quality: str
    file_type: str
    width: int
    height: int
    fps: float
    link: str

    @property
    def resolution(self) -> str:
        return f"{self.width}x{self.height}"

    @property
    def is_portrait(self) -> bool:
        return self.height >= self.width

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class PexelsVideo:
    """Metadata for a matched Pexels video."""
    id: int
    url: str
    duration: int
    tags: List[str]
    user_name: str
    selected_file: Optional[VideoFileCandidate]
    was_fallback: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "url": self.url,
            "duration": self.duration,
            "tags": self.tags,
            "user_name": self.user_name,
            "selected_file": self.selected_file.to_dict() if self.selected_file else None,
            "was_fallback": self.was_fallback,
        }


@dataclass
class ClipMatch:
    """A matched segment pairing the generated query with Pexels footage."""
    clip_index: int
    query: ClipQuery
    video: Optional[PexelsVideo]
    download_path: Optional[str] = None
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "clip_index": self.clip_index,
            "query": self.query.to_dict(),
            "video": self.video.to_dict() if self.video else None,
            "download_path": self.download_path,
            "error": self.error,
        }


@dataclass
class StockMatcherResult:
    """Overall outcome of the stock matching process."""
    script_segment: str
    duration_seconds: float
    clip_count: int
    model_used: str
    matches: List[ClipMatch] = field(default_factory=list)
    execution_time_seconds: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "script_segment": self.script_segment,
            "duration_seconds": self.duration_seconds,
            "clip_count": self.clip_count,
            "model_used": self.model_used,
            "execution_time_seconds": round(self.execution_time_seconds, 2),
            "matches": [m.to_dict() for m in self.matches],
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)


# ============================================================================
# Used-video registry (shared across concurrent match() calls)
# ============================================================================


class UsedVideoIds:
    """The Pexels video ids already committed to one plan.

    Why a class and not a bare ``set``: ``engine/media/clips.py`` runs beats
    through a 4-worker ``ThreadPoolExecutor`` sharing one
    ``StockVideoMatcherAgent``, so this is shared mutable state written from
    four threads. ``if vid not in used: used.add(vid)`` is two operations
    with a window between them, and two threads can both pass the ``not in``
    before either ``add`` -- which is exactly how the same clip lands in two
    beats. ``reserve`` closes that window by doing the test and the set
    together under one lock, and returning whether *this* caller is the one
    that got it.

    The lock lives on the registry rather than on the agent, so the thing
    being guarded and the thing doing the guarding cannot drift apart: there
    is no path to the id set that does not go through it.

    One registry is one plan (see ``generate_plan_clips``). Two different
    videos are free to use the same footage; only one video may not repeat
    itself.
    """

    __slots__ = ("_ids", "_lock")

    def __init__(self, ids: Optional[Any] = None) -> None:
        self._lock = threading.Lock()
        self._ids: set = set(ids or ())

    def reserve(self, video_id: int) -> bool:
        """Claim ``video_id``; return True only for the caller that got it.

        Atomic test-and-set. Callers reserve *before* downloading, so an id
        is spoken for from the instant it is selected -- a download that
        later fails does not release it, because handing a known-bad
        candidate back to another beat only costs a second failure.
        """
        with self._lock:
            if video_id in self._ids:
                return False
            self._ids.add(video_id)
            return True

    def snapshot(self) -> set:
        """A copy of the ids claimed so far, safe to read without the lock.

        It is a copy, not a view: the caller hands it to a network search
        that takes seconds, during which other threads keep reserving. A
        stale snapshot can only cause a *redundant* selection, which
        ``reserve`` then rejects; it can never cause a duplicate.
        """
        with self._lock:
            return set(self._ids)

    def __contains__(self, video_id: object) -> bool:
        with self._lock:
            return video_id in self._ids

    def __len__(self) -> int:
        with self._lock:
            return len(self._ids)

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"UsedVideoIds({sorted(self.snapshot())})"


# ============================================================================
# Visual Query Generator (OmniRoute / OpenAI SDK)
# ============================================================================


class VisualQueryGenerator:
    """Converts script segments into concrete, physical-only search queries via OmniRoute."""

    SYSTEM_PROMPT = """You are a visual director specializing in hyper-engaging vertical short-form video (FactoHolic / YouTube Shorts / Reels style).
Your task is to convert voiceover script segments into precise, visual-only stock footage search queries.

CRITICAL RULES:
1. Fast-cut pacing: Output EXACTLY {clip_count} queries (one for every 2.5 seconds of narration).
2. Word count: Each query MUST be between 3 and 5 words maximum in English.
3. CONCRETE PHYSICAL VISUALS ONLY:
   - Describe only physical objects, environments, camera movements, textures, and visible actions that a camera lens can record.
   - Example good queries: "drone aerial luxury mansion", "counting dollar bills hands", "private jet interior", "futuristic server room glowing", "person opening steel vault".
4. STRICT BAN ON ABSTRACT & EMOTIONAL WORDS:
   - You MUST NOT use abstract concepts, emotions, or buzzwords.
   - BANNED WORDS include: "expensive", "crazy", "shocking", "history", "wealthy", "rich", "poor", "sad", "happy", "secret", "dangerous", "unbelievable", "amazing", "success", "power", "mind-blowing", "financial".
   - Instead of "expensive mansion" -> use "drone aerial luxury mansion"
   - Instead of "crazy money" -> use "counting dollar bills hands"
   - Instead of "shocking secret document" -> use "hands opening classified dossier"
   - Instead of "ancient history" -> use "pyramids desert sand golden hour"
5. OUTPUT FORMAT:
   Return valid, parsable JSON ONLY without any additional explanation or conversational text, adhering to this schema:
   {
     "clips": [
       {
         "clip_index": 1,
         "search_query": "3 to 5 words visual query",
         "shot_intent": "brief 1-sentence description of the visual scene"
       }
     ]
   }
"""

    def __init__(
        self,
        base_url: Optional[str] = None,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        timeout: float = 30.0,
    ) -> None:
        if not OPENAI_AVAILABLE:
            raise ImportError(
                "The `openai` package is required. Install it using: pip install openai"
            )

        # Environment variable precedence: explicit -> OMNIROUTE_BASE_URL -> OMNIROUTE_BASE -> default
        self.base_url = (
            base_url
            or os.getenv("OMNIROUTE_BASE_URL")
            or os.getenv("OMNIROUTE_BASE")
            or "http://127.0.0.1:20128/v1"
        )
        self.api_key = (
            api_key
            or os.getenv("OMNIROUTE_API_KEY")
            or os.getenv("OMNIROUTE_KEY")
            or "omniroute"
        )
        self.model = (
            model
            or os.getenv("OMNIROUTE_MODEL")
            or os.getenv("RAHASYA_MODEL_CHEAP")
            or "agy/gemini-3.7-flash-medium"
        )
        self.timeout = timeout

        self.client = OpenAI(
            base_url=self.base_url,
            api_key=self.api_key,
            timeout=self.timeout,
        )

    def calculate_clip_count(self, duration_seconds: float) -> int:
        """Calculate clip count: math.ceil(duration_seconds / 2.5)."""
        duration = max(1.0, float(duration_seconds))
        return max(1, math.ceil(duration / 2.5))

    def _sanitize_query(self, raw_query: str) -> str:
        """Sanitize query: remove punctuation, ban list words, enforce 3-5 words."""
        # Strip quotes and punctuation
        clean = re.sub(r'[^\w\s]', ' ', raw_query).strip()
        words = clean.split()

        # Filter out banned words (case-insensitive)
        filtered_words = [w for w in words if w.lower() not in BANNED_WORDS]

        # If too few words after filtering, fallback to non-banned or basic visuals
        if not filtered_words:
            filtered_words = ["cinematic", "visual", "shot"]

        # Enforce 3 to 5 words
        if len(filtered_words) > 5:
            filtered_words = filtered_words[:5]
        elif len(filtered_words) < 3:
            # Pad with complementary physical terms if needed
            fillers = ["4k", "cinematic", "macro", "detail"]
            for filler in fillers:
                if len(filtered_words) >= 3:
                    break
                if filler not in filtered_words:
                    filtered_words.append(filler)

        return " ".join(filtered_words).lower()

    def _scene_query(self, script_segment: str) -> str:
        """A Pexels query cut from the beat's own scene description.

        ``script_segment`` is ``beat.visual_prompt`` -- an English shot
        description the script agent wrote for exactly this purpose. It is
        a sentence, not a query, so the function words come out first;
        _sanitize_query then applies the ban list and the 3-5 word rule to
        what is left.

        Stopwords are stripped here rather than inside _sanitize_query
        because a query the model wrote is already three to five content
        words, and running this over it could only damage it.
        """
        words = [w for w in re.sub(r"[^\w\s]", " ", script_segment).split()
                 if w.lower() not in SCENE_STOPWORDS]
        # Everything was a stopword: hand the original over and let
        # _sanitize_query's own padding deal with it. Degenerate, but a
        # beat must not die here.
        return self._sanitize_query(" ".join(words) or script_segment)

    def _queries_from_scene(
        self, script_segment: str, clip_count: int, why: str
    ) -> List[Dict[str, Any]]:
        """Fill every slot from the scene description, and say so.

        One query for all the slots rather than a different guess per
        slot: there is only one description, and inventing variations on
        it would be making things up. The slots still get different
        footage -- the plan's used-id registry refuses to hand the same
        Pexels video to two slots, so one query returns the next-best
        match each time.

        The ``shot_intent`` names the source on purpose. The fallback this
        replaces was invisible -- it looked exactly like a working result
        on the review board, which is why nobody noticed the queries were
        the model's small talk. This one announces itself on every card.
        """
        print(f"[queries] falling back to the beat's scene: {why}",
              flush=True)
        query = self._scene_query(script_segment)
        return [
            {
                "clip_index": i + 1,
                "search_query": query,
                "shot_intent": ("From the beat's scene — the model "
                                "returned no queries"),
            }
            for i in range(clip_count)
        ]

    def generate_queries(
        self, script_segment: str, duration_seconds: float
    ) -> Tuple[List[ClipQuery], int]:
        """Generate structured visual queries from the script segment."""
        clip_count = self.calculate_clip_count(duration_seconds)
        system_prompt = self.SYSTEM_PROMPT.replace("{clip_count}", str(clip_count))
        user_prompt = f"VOICEOVER SCRIPT SEGMENT ({duration_seconds:.1f}s):\n\"{script_segment}\""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.3,
            )
        except (APIError, APIConnectionError, APITimeoutError,
                RateLimitError) as exc:
            # A dead gateway is the case the scene fallback is worth most
            # in: no model at all, and a perfectly good English shot
            # description already in hand. Raising here instead would drop
            # the whole beat to a generated still.
            parsed_clips = self._queries_from_scene(
                script_segment, clip_count,
                f"{type(exc).__name__}: {exc}")
        else:
            content = response.choices[0].message.content or ""
            try:
                parsed_clips = self._parse_json_response(content, clip_count)
            except ValueError as exc:
                parsed_clips = self._queries_from_scene(
                    script_segment, clip_count, str(exc))

        # Sanitize and post-process
        validated_queries: List[ClipQuery] = []
        for idx, item in enumerate(parsed_clips, start=1):
            raw_query = item.get("search_query", "")
            shot_intent = item.get("shot_intent", "Visual scene support")
            clean_query = self._sanitize_query(raw_query)
            validated_queries.append(
                ClipQuery(
                    clip_index=idx,
                    search_query=clean_query,
                    shot_intent=shot_intent,
                )
            )

        return validated_queries, clip_count

    def generate_mock_queries(
        self, script_segment: str, duration_seconds: float
    ) -> Tuple[List[ClipQuery], int]:
        """Generate deterministic, high-quality visual queries for mock/offline testing."""
        clip_count = self.calculate_clip_count(duration_seconds)
        visual_pool = [
            ("drone aerial mountain fortress", "Establishing shot of remote mountain complex"),
            ("heavy steel vault door", "Close-up of industrial security door locking mechanism"),
            ("gold bars stacked rows", "Camera dolly over gleaming metal ingots"),
            ("security laser beams corridor", "Low angle of high-tech surveillance hallway"),
            ("counting dollar bills hands", "Close-up of currency passing rapidly through fingers"),
            ("private jet hangar exterior", "Wide view of private aircraft on runway tarmac"),
            ("futuristic server room glowing", "Dolly shot down dark server aisles with blue LEDs"),
            ("hands typing glowing keyboard", "Macro shot of fingers entering security codes"),
        ]
        queries: List[ClipQuery] = []
        for i in range(clip_count):
            query_tuple = visual_pool[i % len(visual_pool)]
            clean_q = self._sanitize_query(query_tuple[0])
            queries.append(
                ClipQuery(
                    clip_index=i + 1,
                    search_query=clean_q,
                    shot_intent=query_tuple[1],
                )
            )
        return queries, clip_count

    def _parse_json_response(self, content: str, expected_count: int) -> List[Dict[str, Any]]:
        """Parse structured JSON from model response with fallback extraction."""
        # Clean markdown codeblocks
        cleaned = content.strip()
        if "```" in cleaned:
            match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", cleaned)
            if match:
                cleaned = match.group(1).strip()

        try:
            data = json.loads(cleaned)
            if isinstance(data, dict) and "clips" in data and isinstance(data["clips"], list):
                return data["clips"]
            if isinstance(data, list):
                return data
        except json.JSONDecodeError:
            pass

        # Fallback: regex search for clip-like JSON objects
        matches = re.findall(
            r'\{\s*"clip_index"\s*:\s*\d+\s*,\s*"search_query"\s*:\s*"([^"]+)"\s*,\s*"shot_intent"\s*:\s*"([^"]+)"\s*\}',
            content,
        )
        if matches:
            return [
                {"clip_index": i + 1, "search_query": q, "shot_intent": intent}
                for i, (q, intent) in enumerate(matches)
            ]

        # No JSON anywhere: the model chatted instead of answering, and
        # there is nothing here to recover.
        #
        # This used to read the prose line by line, strip the punctuation
        # off each line and search Pexels for whatever was left, which
        # turned "Here's a 4:1 breakdown" into the query "here s a 4 1".
        # Every such line is a valid Pexels search that returns real
        # footage, so the run reported success and the board filled with
        # video chosen for the model's small talk.
        #
        # Refusing costs the beat nothing it was actually getting.
        # generate_plan_clips catches a raise per beat and falls back to
        # the generated-still chain, which draws for *this* beat -- so the
        # old fallback never saved a beat, it only swapped a visibly
        # missing clip for an invisibly wrong one.
        raise ValueError(
            f"the model did not return JSON, so there are no queries to "
            f"read. Asked for {expected_count} clips and got back:\n"
            f"{content.strip()[:400] or '(an empty reply)'}")


# ============================================================================
# Pexels Video Fetcher & Re-ranker
# ============================================================================

# The renderer's output frame size, in pixels (1080x1920). This MUST match
# engine/media rendering's actual output resolution: every downloaded clip is
# scaled to this size before compositing, so picking a source file far above
# it only burns bandwidth/disk/CPU on pixels that get thrown away, and picking
# one below it forces an upscale that never looks as good as a downscale.
RENDER_TARGET_WIDTH = 1080
RENDER_TARGET_HEIGHT = 1920
RENDER_TARGET_PIXELS = RENDER_TARGET_WIDTH * RENDER_TARGET_HEIGHT  # 2,073,600

# _select_best_video scoring bands (see the resolution-scoring comment
# there for the full rationale). The orientation bonus must stay the
# dominant term: a correctly-oriented file must outscore a wrongly-oriented
# one no matter what the other terms award. Those other terms are the
# resolution score AND the HD-quality bonus, and they are summed, so the
# comparison that matters is against their combined maximum
# (_RESOLUTION_COVER_CEILING + _HD_QUALITY_BONUS = 4,500,000), not against
# the resolution term alone. Real headroom under ORIENTATION_BONUS is
# 500,000. Within the resolution term, the "covers the target" band is
# [_RESOLUTION_COVER_FLOOR, _RESOLUTION_COVER_CEILING] = [2,000,000,
# 4,000,000] and the "undersized" band is [0, _RESOLUTION_UNDERSIZED_CEILING)
# = [0, 1,000,000) — the bands don't overlap, so every covering file
# outscores every undersized one.
#
# These asserts document the invariants; note they are stripped under
# `python -O`, so they are a statement of intent for whoever edits the
# numbers, not a runtime guard. Keep them honest.
ORIENTATION_BONUS = 5_000_000.0
_RESOLUTION_COVER_CEILING = 4_000_000.0
_RESOLUTION_COVER_FLOOR = 2_000_000.0
_RESOLUTION_UNDERSIZED_CEILING = 1_000_000.0
# Awarded on top of the resolution score when Pexels flags a file "hd".
_HD_QUALITY_BONUS = 500_000.0
assert _RESOLUTION_COVER_CEILING + _HD_QUALITY_BONUS < ORIENTATION_BONUS
assert _RESOLUTION_UNDERSIZED_CEILING < _RESOLUTION_COVER_FLOOR < _RESOLUTION_COVER_CEILING


class PexelsFetcher:
    """Queries Pexels Videos API with portrait filters, HD MP4 selection, and landscape fallback."""

    BASE_URL = "https://api.pexels.com/videos/search"

    def __init__(self, api_key: Optional[str] = None, timeout: float = 15.0) -> None:
        self.api_key = api_key or os.getenv("PEXELS_API_KEY") or ""
        self.timeout = timeout

        self.session = requests.Session()
        retries = Retry(
            total=3,
            backoff_factor=1.0,
            status_forcelist=[429, 500, 502, 503, 504],
            allowed_methods=["GET"],
        )
        self.session.mount("https://", HTTPAdapter(max_retries=retries))

    def _headers(self) -> Dict[str, str]:
        if not self.api_key:
            raise ValueError(
                "PEXELS_API_KEY is not set. Please add it to your .env file or pass api_key."
            )
        return {"Authorization": self.api_key}

    # A search that has to avoid ids already spent on this plan needs more
    # than one candidate to choose between. per_page=5 hands the ranker five
    # videos; once some of them are used, "the best remaining" is easily
    # "none", and a slot that could have carried different footage falls
    # back to a still instead. Asking for a bigger page is the cheapest way
    # to substitute rather than fall back: the same request, more rows, and
    # only when an exclusion is actually in play.
    EXCLUDED_PER_PAGE = 15

    def search_video(
        self,
        query: str,
        orientation: str = "portrait",
        per_page: int = 5,
        exclude_ids: Optional[Any] = None,
    ) -> Tuple[Optional[PexelsVideo], bool]:
        """Search Pexels for a query with portrait priority and landscape fallback.

        ``exclude_ids`` is an iterable of Pexels video ids already used
        elsewhere in this plan. It reaches all the way into the ranker
        (``_select_best_video``) rather than filtering the winner
        afterwards, and that is the whole point: this method returns exactly
        one video, so a caller that only saw the winner could reject a
        duplicate but never replace it -- and a rejected slot is a fallback
        still, strictly worse than different footage.

        A tier whose every candidate is excluded is treated like a tier that
        returned nothing, so the existing fallback chain (portrait ->
        landscape -> unfiltered -> simplified query) doubles as the
        broadening strategy when a query's best results are already spent.

        Returns:
            Tuple of (PexelsVideo or None, was_fallback_boolean)
        """
        excluded = set(exclude_ids or ())
        page_size = max(per_page, self.EXCLUDED_PER_PAGE) if excluded else per_page

        # (query, orientation, counts_as_fallback), best first.
        tiers: List[Tuple[str, Optional[str], bool]] = [(query, orientation, False)]
        if orientation == "portrait":
            tiers.append((query, "landscape", True))
        tiers.append((query, None, True))
        simplified_query = " ".join(query.split()[:2])
        if simplified_query and simplified_query != query:
            tiers.append((simplified_query, None, True))

        was_fallback = False
        for tier_query, tier_orientation, counts_as_fallback in tiers:
            videos, _ = self._execute_search(
                tier_query, orientation=tier_orientation, per_page=page_size
            )
            if counts_as_fallback:
                was_fallback = True
            if not videos:
                continue

            # Re-rank and extract the best MP4 file from the matching videos
            best_video = self._select_best_video(
                videos,
                target_portrait=(orientation == "portrait"),
                exclude_ids=excluded,
            )
            if best_video:
                best_video.was_fallback = was_fallback
                return best_video, was_fallback

        return None, was_fallback

    # How many alternative ids the mock catalogue offers past the one a clip
    # index asks for. Far more than any plan has slots (a 60s reel is ~24),
    # so the offline path exercises substitution rather than starvation --
    # but bounded, so exhaustion is still reachable and still reported the
    # way a real exhausted search reports it.
    MOCK_ALTERNATIVES = 256

    def mock_video(
        self,
        query: str,
        clip_index: int = 1,
        exclude_ids: Optional[Any] = None,
    ) -> Tuple[Optional[PexelsVideo], bool]:
        """Return simulated portrait HD video result for offline testing.

        ``exclude_ids`` mirrors ``search_video``: the mock walks forward to
        the first id it has not already handed out. Without it the offline
        path returns id 2000+clip_index to *every* beat, which is the
        duplication this module exists to prevent -- an offline test of
        deduplication would then be testing nothing.
        """
        excluded = set(exclude_ids or ())
        offset = clip_index
        ceiling = clip_index + self.MOCK_ALTERNATIVES
        while 2000 + offset in excluded and offset < ceiling:
            offset += 1
        if 2000 + offset in excluded:
            # Catalogue exhausted. Same shape as a real search that found
            # nothing unused, so the caller handles the two identically.
            return None, False

        sample_file = VideoFileCandidate(
            id=1000 + offset,
            quality="hd",
            file_type="video/mp4",
            width=1080,
            height=1920,
            fps=30.0,
            link=f"https://static.pexels.com/mock/clip_{offset:02d}_1080x1920.mp4",
        )
        video = PexelsVideo(
            id=2000 + offset,
            url=f"https://www.pexels.com/video/{2000 + offset}/",
            duration=15,
            tags=query.split(),
            user_name="StockCinematographer",
            selected_file=sample_file,
            was_fallback=False,
        )
        return video, False

    def _execute_search(
        self,
        query: str,
        orientation: Optional[str] = None,
        per_page: int = 5,
    ) -> Tuple[List[Dict[str, Any]], bool]:
        """Execute HTTP GET to Pexels video search endpoint."""
        params: Dict[str, Any] = {"query": query, "per_page": per_page}
        if orientation:
            params["orientation"] = orientation

        try:
            resp = self.session.get(
                self.BASE_URL,
                headers=self._headers(),
                params=params,
                timeout=self.timeout,
            )
            resp.raise_for_status()
            data = resp.json()
            return data.get("videos", []), False
        except requests.RequestException as err:
            # Handle rate limit or network timeout
            if isinstance(err, requests.HTTPError) and err.response is not None and err.response.status_code == 401:
                raise ValueError("Invalid PEXELS_API_KEY. Please verify your Pexels credentials.") from err
            return [], False

    def _select_best_video(
        self,
        videos: List[Dict[str, Any]],
        target_portrait: bool = True,
        exclude_ids: Optional[Any] = None,
    ) -> Optional[PexelsVideo]:
        """Select the highest resolution MP4 matching target orientation from candidate videos.

        ``exclude_ids`` drops videos already used elsewhere in the plan out
        of the competition entirely. Filtering here rather than at the caller
        is what turns "this slot is a duplicate" into "this slot gets the
        next best video".
        """
        excluded = set(exclude_ids or ())
        best_video_obj: Optional[PexelsVideo] = None
        highest_score = -1.0

        for vid in videos:
            video_id = vid.get("id", 0)
            if video_id in excluded:
                continue
            url = vid.get("url", "")
            duration = int(vid.get("duration", 0))
            tags = [t.get("name", "") if isinstance(t, dict) else str(t) for t in vid.get("tags", [])]
            user = vid.get("user", {})
            user_name = user.get("name", "") if isinstance(user, dict) else ""

            # Evaluate video_files
            video_files = vid.get("video_files", [])
            best_file: Optional[VideoFileCandidate] = None
            best_file_score = -1.0

            for f in video_files:
                file_type = f.get("file_type", "")
                link = f.get("link", "")
                
                # Must be MP4
                if file_type != "video/mp4" and not link.endswith(".mp4"):
                    continue

                width = int(f.get("width") or 0)
                height = int(f.get("height") or 0)
                fps = float(f.get("fps") or 0.0)
                quality = str(f.get("quality") or "sd").lower()

                if width <= 0 or height <= 0 or not link:
                    continue

                # Scoring criteria:
                # 1. Aspect ratio: bonus if matches target orientation
                is_portrait = height >= width
                score = 0.0
                if target_portrait and is_portrait:
                    score += ORIENTATION_BONUS
                elif not target_portrait and not is_portrait:
                    score += ORIENTATION_BONUS

                # 2. Prefer the smallest file that still covers the render
                # target (1080x1920) over the largest one available: every
                # pixel above the target is downloaded, decoded and then
                # scaled away by the renderer, so "biggest wins" wastes
                # bandwidth/disk/time for no visual benefit.
                #
                # - At/above target: closer to the target (from above) is
                #   better. Score falls off monotonically as pixel_count
                #   grows past the target, so a smaller covering file always
                #   outscores a larger one, but the score is floored at
                #   _RESOLUTION_COVER_FLOOR so it can never sink into (let
                #   alone below) the undersized band.
                # - Below target: acceptable only when nothing covers the
                #   target; among those, bigger is better (less upscaling),
                #   but the whole band is capped by _RESOLUTION_UNDERSIZED_CEILING,
                #   which sits strictly below _RESOLUTION_COVER_FLOOR — so no
                #   undersized file can ever outscore a covering one.
                #
                # The resolution term's maximum (_RESOLUTION_COVER_CEILING)
                # plus the HD bonus is kept strictly below ORIENTATION_BONUS
                # (see the constants), so a correctly-oriented file always
                # beats a wrongly-oriented one regardless of resolution or
                # quality flag.
                pixel_count = width * height
                if pixel_count >= RENDER_TARGET_PIXELS:
                    coverage_ratio = RENDER_TARGET_PIXELS / pixel_count  # (0, 1], 1.0 = exact match
                    resolution_score = _RESOLUTION_COVER_FLOOR + (
                        _RESOLUTION_COVER_CEILING - _RESOLUTION_COVER_FLOOR
                    ) * coverage_ratio
                else:
                    undersize_ratio = pixel_count / RENDER_TARGET_PIXELS  # [0, 1)
                    resolution_score = _RESOLUTION_UNDERSIZED_CEILING * undersize_ratio
                score += resolution_score

                # 3. Quality flag bonus
                if quality == "hd":
                    score += _HD_QUALITY_BONUS

                if score > best_file_score:
                    best_file_score = score
                    best_file = VideoFileCandidate(
                        id=f.get("id", 0),
                        quality=quality,
                        file_type=file_type,
                        width=width,
                        height=height,
                        fps=fps,
                        link=link,
                    )

            if best_file and best_file_score > highest_score:
                highest_score = best_file_score
                best_video_obj = PexelsVideo(
                    id=video_id,
                    url=url,
                    duration=duration,
                    tags=tags,
                    user_name=user_name,
                    selected_file=best_file,
                )

        return best_video_obj


# ============================================================================
# Download Pipeline
# ============================================================================


class ClipDownloader:
    """Streams and downloads video files sequentially with progress tracking."""

    def __init__(self, output_dir: str = "output_clips", timeout: float = 60.0) -> None:
        self.output_dir = Path(output_dir)
        self.timeout = timeout
        self.session = requests.Session()

    def download_clip(
        self,
        url: str,
        clip_index: int,
        progress: Optional[Progress] = None,
        task_id: Any = None,
        output_dir: Optional[Union[str, Path]] = None,
    ) -> Path:
        """Download video from URL directly into <output_dir>/clip_{index:02d}.mp4 atomically.

        ``output_dir`` is per call and overrides ``self.output_dir``. It
        exists because a single downloader is shared by concurrent
        ``StockVideoMatcherAgent.match()`` calls: a destination *stored* on
        the instance is whatever the most recent caller wrote there, which
        sent one beat's clips into another beat's folder (and raced on the
        ``.tmp`` staging path, so a half-written file could be renamed over
        a finished one). A destination *passed* cannot be clobbered by
        another thread. ``self.output_dir`` remains the default for
        single-threaded callers.
        """
        target_dir = Path(output_dir) if output_dir is not None else self.output_dir
        target_dir.mkdir(parents=True, exist_ok=True)
        filename = f"clip_{clip_index:02d}.mp4"
        final_path = target_dir / filename
        temp_path = target_dir / f"{filename}.tmp"

        # Fast-path for mock testing URLs
        if url.startswith("https://static.pexels.com/mock/") or url.startswith("mock://"):
            mock_bytes = b"\x00\x00\x00\x20ftypisom\x00\x00\x02\x00isomiso2avc1mp41" + (b"\x00" * (1024 * 128))
            if progress and task_id is not None:
                progress.update(task_id, total=len(mock_bytes))
                progress.update(task_id, advance=len(mock_bytes))
            final_path.write_bytes(mock_bytes)
            return final_path

        try:
            with self.session.get(url, stream=True, timeout=self.timeout) as response:
                response.raise_for_status()
                total_size = int(response.headers.get("content-length", 0))

                if progress and task_id is not None:
                    progress.update(task_id, total=total_size)

                with open(temp_path, "wb") as f:
                    for chunk in response.iter_content(chunk_size=1024 * 64):
                        if chunk:
                            f.write(chunk)
                            if progress and task_id is not None:
                                progress.update(task_id, advance=len(chunk))

            # Atomic rename once complete
            temp_path.replace(final_path)
            return final_path
        except Exception:
            if temp_path.exists():
                temp_path.unlink()
            raise


# ============================================================================
# Main Agent Orchestrator
# ============================================================================


class StockVideoMatcherAgent:
    """End-to-end AI-Powered Stock Video Matcher Agent."""

    def __init__(
        self,
        omniroute_base_url: Optional[str] = None,
        omniroute_api_key: Optional[str] = None,
        omniroute_model: Optional[str] = None,
        pexels_api_key: Optional[str] = None,
    ) -> None:
        self.query_generator = VisualQueryGenerator(
            base_url=omniroute_base_url,
            api_key=omniroute_api_key,
            model=omniroute_model,
        )
        self.pexels_fetcher = PexelsFetcher(api_key=pexels_api_key)
        self.downloader = ClipDownloader()

    # How many times one query may re-select after losing a reservation
    # race. Every loss means another thread reserved that exact id, so the
    # next snapshot excludes it and the retry makes progress -- the cap only
    # bounds a pathological pile-up. The pool is four workers, so three
    # consecutive losses is already the realistic worst case.
    MAX_SELECTION_ATTEMPTS = 8

    def _fetch_video(
        self,
        query: ClipQuery,
        exclude_ids: Optional[Any],
        mock: bool,
    ) -> Tuple[Optional[PexelsVideo], bool]:
        """One selection attempt for one query, live or mocked."""
        if mock or not self.pexels_fetcher.api_key:
            return self.pexels_fetcher.mock_video(
                query=query.search_query,
                clip_index=query.clip_index,
                exclude_ids=exclude_ids,
            )
        return self.pexels_fetcher.search_video(
            query=query.search_query,
            orientation="portrait",
            per_page=5,
            exclude_ids=exclude_ids,
        )

    def _select_unused_video(
        self,
        query: ClipQuery,
        used: Optional[UsedVideoIds],
        mock: bool,
    ) -> Tuple[Optional[PexelsVideo], bool]:
        """Pick a video for ``query`` that no other slot in the plan holds.

        The window this closes: selection takes seconds (a Pexels round
        trip), so two threads can search against the same snapshot and pick
        the same video before either has recorded it. The snapshot alone
        cannot prevent that -- nothing can, since both searches are already
        in flight. What decides it is ``reserve``, an atomic test-and-set
        run the instant a video is chosen and *before* the download: exactly
        one caller gets True, and the loser simply selects again against a
        fresh snapshot that now contains the winner's id, coming back with
        different footage rather than an empty slot.

        Reserving before downloading also means a failed download keeps its
        id reserved. That is deliberate: releasing it would only offer a
        known-bad candidate to the next beat, and a release racing another
        thread's snapshot re-opens the same window for no gain.
        """
        if used is None:
            return self._fetch_video(query, None, mock)

        was_fallback = False
        for _ in range(self.MAX_SELECTION_ATTEMPTS):
            video, was_fallback = self._fetch_video(query, used.snapshot(), mock)
            if video is None:
                # Every candidate this query can reach is already used.
                # Reported as "no video", which the clip layer turns into a
                # fallback still -- never into a repeat.
                return None, was_fallback
            if used.reserve(video.id):
                return video, was_fallback
            # Lost the race for this id. Loop: the next snapshot contains
            # it, so the search is forced onto a different video.
        return None, was_fallback

    def match(
        self,
        script_segment: str,
        duration_seconds: float,
        download: bool = False,
        output_dir: str = "output_clips",
        on_query_ready: Optional[Any] = None,
        mock: bool = False,
        used_video_ids: Optional[UsedVideoIds] = None,
    ) -> StockMatcherResult:
        """Synchronously match stock footage to script segment.

        Args:
            script_segment: The voiceover narration text.
            duration_seconds: Runtime in seconds.
            download: If True, downloads MP4s to output_dir.
            output_dir: Folder to save downloaded MP4 clips.
            on_query_ready: Optional callback receiving generated queries.
            mock: If True, uses deterministic offline mock generation.
            used_video_ids: A ``UsedVideoIds`` registry shared by every
                ``match()`` call belonging to one plan. Ids in it are
                excluded from selection and every id this call keeps is
                added to it, so no Pexels video carries two slots of the
                same video. ``None`` (the default, and what the CLI uses)
                disables deduplication entirely and leaves behaviour
                exactly as it was.

        Returns:
            StockMatcherResult containing all queries, matches, and file paths.
        """
        used = used_video_ids
        if used is not None and not isinstance(used, UsedVideoIds):
            # A bare set would look like it worked and quietly race: "not in
            # / add" is two operations, and this method runs on four threads
            # at once. Refuse it at the door rather than ship a check that
            # holds only when nobody is in a hurry.
            raise TypeError(
                "used_video_ids must be a UsedVideoIds registry, not "
                f"{type(used_video_ids).__name__}: a plain set cannot be "
                "test-and-set atomically and match() is called concurrently."
            )
        start_time = time.time()
        # output_dir is carried in a local and handed to each download_clip
        # call below; it is deliberately NOT stored on self.downloader.
        # match() is re-entrant: engine/pipeline.py builds ONE agent and
        # engine/media/clips.generate_plan_clips runs beats through a
        # 4-worker pool, and seconds pass between here and the downloads —
        # an LLM round trip plus a Pexels search per clip. Recording the
        # destination on the shared downloader therefore meant a beat
        # downloaded into whichever directory the most recently *started*
        # call had asked for, not its own: clip_NN.mp4 names collided
        # across beats again, and the clip_NN.mp4.tmp staging path raced,
        # so a half-written file could be renamed over a finished one.
        # Nothing here may mutate self (or anything reachable from it).

        # 1. Generate queries via OmniRoute or Mock
        if mock:
            queries, clip_count = self.query_generator.generate_mock_queries(
                script_segment=script_segment,
                duration_seconds=duration_seconds,
            )
        else:
            queries, clip_count = self.query_generator.generate_queries(
                script_segment=script_segment,
                duration_seconds=duration_seconds,
            )

        if on_query_ready:
            on_query_ready(queries)

        matches: List[ClipMatch] = []

        # 2. Fetch stock videos for each query
        for query in queries:
            try:
                matched_video, was_fallback = self._select_unused_video(
                    query, used=used, mock=mock
                )
                if matched_video:
                    error = None
                elif used is not None:
                    error = (
                        "No unused stock video found for query: every candidate "
                        "is already used elsewhere in this plan"
                    )
                else:
                    error = "No stock video found for query"
                match_entry = ClipMatch(
                    clip_index=query.clip_index,
                    query=query,
                    video=matched_video,
                    error=error,
                )
            except Exception as exc:
                match_entry = ClipMatch(
                    clip_index=query.clip_index,
                    query=query,
                    video=None,
                    error=str(exc),
                )
            matches.append(match_entry)

        # 3. Optional download pipeline
        if download:
            for match in matches:
                if match.video and match.video.selected_file:
                    try:
                        saved_path = self.downloader.download_clip(
                            url=match.video.selected_file.link,
                            clip_index=match.clip_index,
                            output_dir=output_dir,
                        )
                        match.download_path = str(saved_path)
                    except Exception as err:
                        match.error = f"Download failed: {err}"

        elapsed = time.time() - start_time
        return StockMatcherResult(
            script_segment=script_segment,
            duration_seconds=duration_seconds,
            clip_count=clip_count,
            model_used=self.query_generator.model if not mock else "mock-generator",
            matches=matches,
            execution_time_seconds=elapsed,
        )

    async def match_async(
        self,
        script_segment: str,
        duration_seconds: float,
        download: bool = False,
        output_dir: str = "output_clips",
        mock: bool = False,
        used_video_ids: Optional[UsedVideoIds] = None,
    ) -> StockMatcherResult:
        """Asynchronously execute matching via asyncio thread pool.

        ``used_video_ids`` is forwarded unchanged; the registry is
        thread-safe, which is exactly what a thread-pool caller needs.
        """
        return await asyncio.to_thread(
            self.match,
            script_segment=script_segment,
            duration_seconds=duration_seconds,
            download=download,
            output_dir=output_dir,
            mock=mock,
            used_video_ids=used_video_ids,
        )


# ============================================================================
# CLI Presentation Helpers
# ============================================================================


def render_rich_output(
    console: Console,
    result: StockMatcherResult,
    show_downloads: bool = False,
) -> None:
    """Render a polished, executive-ready terminal display using Rich."""
    try:
        # Header Banner
        banner = Panel(
            f"[bold cyan]AI-Powered Stock Video Matcher[/bold cyan]\n"
            f"[dim]OmniRoute Gateway ({result.model_used}) + Pexels HD Portrait API[/dim]",
            border_style="cyan",
            expand=False,
        )
        console.print(banner)

        # Input Summary Table
        summary_table = Table(show_header=False, box=None, padding=(0, 2))
        summary_table.add_column("Key", style="bold yellow")
        summary_table.add_column("Value", style="white")

        script_preview = (
            result.script_segment[:90] + "..."
            if len(result.script_segment) > 90
            else result.script_segment
        )
        summary_table.add_row("Script Segment", f'"{script_preview}"')
        summary_table.add_row("Duration", f"{result.duration_seconds:.1f}s")
        summary_table.add_row("Pacing Formula", f"ceil({result.duration_seconds:.1f} / 2.5) = {result.clip_count} cuts")
        summary_table.add_row("Execution Time", f"{result.execution_time_seconds:.2f}s")
        console.print(Panel(summary_table, title="Input & Pacing Overview", border_style="dim"))

        # Results Table
        results_table = Table(
            title="[bold green]Matched Stock Video Timeline[/bold green]",
            border_style="blue",
            header_style="bold magenta",
            expand=True,
        )
        results_table.add_column("#", style="cyan", width=4, justify="center")
        results_table.add_column("Visual Search Query", style="bold white", width=26)
        results_table.add_column("Shot Intent", style="italic dim", width=28)
        results_table.add_column("Status / Fallback", style="yellow", width=18)
        results_table.add_column("Resolution", style="green", width=12)
        results_table.add_column("Pexels Link / Local File", style="blue")

        for m in result.matches:
            idx_str = f"{m.clip_index:02d}"
            query_str = m.query.search_query
            intent_str = m.query.shot_intent

            if m.video and m.video.selected_file:
                file_meta = m.video.selected_file
                status_str = "[green][OK] Portrait[/green]" if not m.video.was_fallback else "[yellow][FALLBACK] Landscape[/yellow]"
                res_str = f"{file_meta.resolution} ({file_meta.quality.upper()})"
                
                if m.download_path:
                    link_display = f"[bold green]Saved:[/bold green] {m.download_path}"
                else:
                    link_display = f"{file_meta.link[:35]}... (Pexels #{m.video.id})"
            else:
                status_str = "[red][FAIL][/red]"
                res_str = "N/A"
                link_display = f"[red]{m.error or 'Not found'}[/red]"

            results_table.add_row(idx_str, query_str, intent_str, status_str, res_str, link_display)

        console.print(results_table)
    except (UnicodeEncodeError, Exception):
        # Fallback to clean formatted JSON if terminal encoding fails
        print(result.to_json(indent=2))


# ============================================================================
# CLI Execution Block
# ============================================================================


def main() -> int:
    parser = argparse.ArgumentParser(
        description="AI-Powered Stock Video Matcher: Convert narration into high-res stock video cuts."
    )
    parser.add_argument(
        "script",
        nargs="?",
        help="Voiceover script segment (or specify via -s / --script).",
    )
    parser.add_argument(
        "-s",
        "--script-text",
        dest="script_flag",
        help="Voiceover script string directly.",
    )
    parser.add_argument(
        "-f",
        "--script-file",
        help="Path to a text file containing the script segment.",
    )
    parser.add_argument(
        "-d",
        "--duration",
        type=float,
        default=7.5,
        help="Voiceover duration in seconds (default: 7.5s -> 3 cuts).",
    )
    parser.add_argument(
        "--download",
        action="store_true",
        help="Download matched MP4 clips to output directory.",
    )
    parser.add_argument(
        "-o",
        "--output-dir",
        default="output_clips",
        help="Directory to save downloaded clips (default: output_clips).",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        dest="output_json",
        help="Output raw JSON format to stdout.",
    )
    parser.add_argument(
        "--model",
        help="Override OmniRoute model name (e.g. agy/gemini-3.7-flash-medium).",
    )
    parser.add_argument(
        "--base-url",
        help="Override OmniRoute base URL.",
    )
    parser.add_argument(
        "--mock",
        "--dry-run",
        action="store_true",
        dest="mock",
        help="Run in mock/offline mode (simulates OmniRoute AI queries and Pexels video metadata).",
    )

    args = parser.parse_args()

    # Determine script content
    script_content = ""
    if args.script_file:
        file_path = Path(args.script_file)
        if not file_path.exists():
            print(f"Error: Script file not found: {args.script_file}", file=sys.stderr)
            return 1
        script_content = file_path.read_text(encoding="utf-8").strip()
    elif args.script_flag:
        script_content = args.script_flag.strip()
    elif args.script:
        script_content = args.script.strip()
    else:
        # Default sample script for fast testing
        script_content = (
            "Deep inside the Swiss Alps lies an ultra-secure subterranean vault, "
            "where billionaires store metric tons of pure gold bars behind twenty-ton blast doors."
        )

    console = Console() if RICH_AVAILABLE else None

    # Check Pexels API key early
    pexels_key = os.getenv("PEXELS_API_KEY")
    if not pexels_key and not args.mock:
        msg = (
            "Notice: PEXELS_API_KEY is not set in environment or .env file.\n"
            "Query generation will succeed, but video search requires a free Pexels key from https://www.pexels.com/api/\n"
            "(Tip: Use --mock to test full visual rendering and downloads offline)."
        )
        if console and not args.output_json:
            console.print(f"[bold yellow]{msg}[/bold yellow]\n")
        else:
            print(msg, file=sys.stderr)

    try:
        agent = StockVideoMatcherAgent(
            omniroute_base_url=args.base_url,
            omniroute_model=args.model,
            pexels_api_key=pexels_key,
        )

        status_msg = (
            "[bold cyan]Generating visual queries via OmniRoute...[/bold cyan]"
            if not args.mock
            else "[bold cyan]Generating mock visual queries and stock video matches...[/bold cyan]"
        )

        # Execute query generation & matching
        if console and not args.output_json:
            with console.status(status_msg):
                result = agent.match(
                    script_segment=script_content,
                    duration_seconds=args.duration,
                    download=False,
                    output_dir=args.output_dir,
                    mock=args.mock,
                )
        else:
            result = agent.match(
                script_segment=script_content,
                duration_seconds=args.duration,
                download=False,
                output_dir=args.output_dir,
                mock=args.mock,
            )

        # Handle downloads with Rich progress if requested
        if args.download:
            # The CLI downloads outside match() (it wants a Rich progress
            # bar per clip), so it names --output-dir itself. match() used
            # to leave the destination on agent.downloader as a side
            # effect; it no longer does, because that shared mutation raced
            # when match() is called concurrently.
            clips_to_download = [m for m in result.matches if m.video and m.video.selected_file]
            if clips_to_download:
                if console and not args.output_json:
                    with Progress(
                        SpinnerColumn(),
                        TextColumn("[progress.description]{task.description}"),
                        BarColumn(),
                        DownloadColumn(),
                        TransferSpeedColumn(),
                        TimeRemainingColumn(),
                        console=console,
                    ) as progress:
                        for m in clips_to_download:
                            task = progress.add_task(
                                f"Downloading clip_{m.clip_index:02d}.mp4",
                                total=None,
                            )
                            try:
                                saved_path = agent.downloader.download_clip(
                                    url=m.video.selected_file.link,
                                    clip_index=m.clip_index,
                                    progress=progress,
                                    task_id=task,
                                    output_dir=args.output_dir,
                                )
                                m.download_path = str(saved_path)
                            except Exception as err:
                                m.error = f"Download failed: {err}"
                else:
                    for m in clips_to_download:
                        try:
                            saved_path = agent.downloader.download_clip(
                                url=m.video.selected_file.link,
                                clip_index=m.clip_index,
                                output_dir=args.output_dir,
                            )
                            m.download_path = str(saved_path)
                        except Exception as err:
                            m.error = f"Download failed: {err}"

        # Output format
        if args.output_json or not RICH_AVAILABLE:
            print(result.to_json(indent=2))
        else:
            render_rich_output(console, result, show_downloads=args.download)

        return 0

    except Exception as err:
        if args.output_json:
            print(json.dumps({"error": str(err)}, indent=2), file=sys.stderr)
        elif console:
            console.print(f"[bold red]Execution Error:[/bold red] {err}")
        else:
            print(f"Error: {err}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
